### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by aldanor**

### CODE REVIEW

**Comment by aldanor** [comment]
This is just a preliminary version, but the core of it seems to work just fine (e.g. see the tests). 

A few particular features to be outlined:

- Any Rust-valid float/int literals are supported, e.g. `-0.1_2_3E+25` (except suffixed literals).
- Hex/oct/bin integers are supported (e.g. `0xff`).
- Compile errors with proper spans highlighted.
- Similar for `fixed::types`, there's `fixed_macros::types` for all specific types; those can be renamed (see the test).
- No extra runtime deps except for `fixed` itself, proc-macro is purely a compile-time plugin.

What's left:

- Add proper, more extensive tests (including compile-fail tests)
- Disallow negative sign token for signed types
- Add some docs and crate metadata
- Set up GitHub Actions for CI
- Consider if a `fixed!(123)` macro without provided type would be worth it - which would only work for integers and make use of type inference in the user code, so that you could use it nicely in the const context. (this would require an additional helper like `const fixed_int()` function defined somewhere, obviously).

// Any comments welcome.

**Comment by tspiteri** [comment]
Very nice! I know basically nothing of proc macros, so I just looked at test_fixed_macros.rs. I have a few comments.

1. Maybe it would be a good idea in the test to include at least one constant to make sure constness is not broken by some change. Probably this is already planned in the first item of *What's left*.
2. The order `fixed!(TYPE: value)` looks reversed to me, as in Rust the type always comes after the colon. In fact, if [RFC 803 (Type ascription)](https://github.com/rust-lang/rfcs/blob/master/text/0803-type-ascription.md) is completed and stabilized, you could even write stuff like `foo.enumerate().collect(): Vec<_>` to make `collect()` return `Vec`. So I think better would be `fixed!(value: TYPE)`.
3. > Consider if a fixed!(123) macro without provided type would be worth it - which would only work for integers

    In case such a macro is added, maybe it would be a good idea to include `int` in the name, otherwise it could be confusing why changing the valid fixed-point number `123` to the equally valid fixed-point number `123.456` breaks compilation.

**Comment by aldanor** [comment]
Thanks for the comments, that's pretty helpful! (I don't have a huge experience with proc-macros either but it's not that hard to figure out as you go as there's tons of examples around)

>     1. Maybe it would be a good idea in the test to include at least one constant to make sure constness is not broken by some change. Probably this is already planned in the first item of _What's left_.
Yep, that's in the plans to add it to tests. But, basically, the generated code looks simply like this `::fixed::types::I24F40::from_bits(128391)`, there's nothing else generated, so it will retain all properties of `from_bits()`.

>     2. The order `fixed!(TYPE: value)` looks reversed to me, as in Rust the type always comes after the colon. In fact, if [RFC 803 (Type ascription)](https://github.com/rust-lang/rfcs/blob/master/text/0803-type-ascription.md) is completed and stabilized, you could even write stuff like `foo.enumerate().collect(): Vec<_>` to make `collect()` return `Vec`. So I think better would be `fixed!(value: TYPE)`.
I had exact same thoughts and was divided between the two options. Maybe `value: TYPE` is better indeed, given the number of contexts you can already encounter it in the language. That should be easy to change.

>        In case such a macro is added, maybe it would be a good idea to include `int` in the name, otherwise it could be confusing why changing the valid fixed-point number `123` to the equally valid fixed-point number `123.456` breaks compilation.
Well, I thought of adding it as a `fixed_int!()`, but it's also possible to stuff it into `fixed!()`, just without the `: TYPE` part. One benefit of proc-macros is that you can emit very clear compile errors and explain things very clearly there, while highlighting the particular parts of the code that caused the fail (kind of like what you see normally in rustc-generated errors and warnings). So would it be still confusing if it highlighted your number and said "only integer literals are supported if you don't provide the explicit type"?

Note that for the type inference in the third part to work (whether it's split into `fixed_int!()` or packed into `fixed!()`), there will need to be an equivalent of `const_fixed_from_int!`, but a generic const fn - still need to think whether it's possible and what's the best way to do it. My idea was that you should be able to simply do `let x: I40F24 = fixed!(123)` - in which case the proc-macro has to have a way to "figure out" the bit shift somehow via the type inference.

**Comment by tspiteri** [comment]
> One benefit of proc-macros is that you can emit very clear compile errors and explain things very clearly there, while highlighting the particular parts of the code that caused the fail (kind of like what you see normally in rustc-generated errors and warnings).

Oh, I wasn't aware. Having a clear error message removes the confusion concern while leaving the API cleaner, nice!

> Note that for the type inference in the third part to work (whether it's split into fixed_int!() or packed into fixed!()), there will need to be an equivalent of const_fixed_from_int!, but a generic const fn

I don't think that's possible currently; if I knew how to do that I would not have added the macro. The macro does not do any inference of the fixed-point type.

**Comment by aldanor** [comment]
@tspiteri A few updates:

- Changed the syntax to `fixed!(<value>: <type>)` (see the docs)
- Added documentation and examples with doctests
- Added a few more tests including const context tests, they now run on CI as well
- Added compile-fail tests, you can see their expected error messages in .stderr files
- Negative literals now get rejected early for unsigned types; removed "+" as a valid starting token
- Re: point (3), as you say, it's probably not possible now due to const functionality being too weak even with const_fn feature enabled; we'll have to wait for a lot longer for it to work it seems.

**Pull request merged**
