### PR TITLE
Fix various scoping issues

### PR DESCRIPTION
**Pull request by aldanor**

### CODE REVIEW

**Comment by aldanor** [comment]
@tspiteri (in the PR that's a scoping bug that I noticed - now fixed)

What I'm wondering about - currently there's a dependency in the root crate:

```toml
fixed = "1"
```

The thing is though, it's not actually used since it's macros all over.

However, in `fixed_macro_impl`, it generates code like `::fixed::types::I32F32::from_bits(123)`, whereas that crate cannot guarantee any runtime dependencies (because all of its dependencies are compile time).

So currently it's neither this nor that.. there's a few options:

1. Remove `fixed` dependency from `fixed-macro`, it will be then upon user to add it (but maybe that's how it should be).

2. (weird option but possible, I'm not sure, may it call any collisions or something, are there some downsides?), do something like

```
// in fixed-macro's lib.rs
#[doc(hidden)]
pub mod __fixed { pub use fixed::types::*}
```

and then in `fixed-macro-impl`, generate code like `::fixed_macro::__fixed::I32F32::from_bits(123)`. Since you will never depend on `fixed-macro-impl` directly, this is sort of guaranteed to be resolved. But then again, this is kind of weird.

**Comment by aldanor** [comment]
@tspiteri Any thoughts re: `fixed` dependency?

**Comment by tspiteri** [comment]
I think option 1 makes more sense, users could list both fixed and fixed-macro as dependencies. The way I understand it is that `fixed!(0.5: I8F8)` is simply a more convenient way to write `::fixed::types::I8F8::from_bits(128)`, so you still need to have `fixed` as a dependency.

But then, I'm not really knowledgeable on this, so I don't favour any option strongly as I simply don't know much.

**Comment by aldanor** [comment]
@tspiteri I did a bit more research, actually it's something close to option 2 that seems to be the standard:

- inside the root crate - doc-hidden pub extern crate: https://github.com/dtolnay/typetag/blob/master/src/lib.rs#L302
- and here's how the codegen looks: https://github.com/dtolnay/typetag/blob/master/impl/src/tagged_impl.rs#L35 
- and the runtime dependency in the root crate: https://github.com/dtolnay/typetag/blob/master/Cargo.toml#L19

I guess this way the user can simply add `fixed-macro` and it will "just work", without failing to compile for some obscure reasons (like "`fixed` missing in `{{root}}`"). Similarly, if they add their own `fixed` dependency (as long as it's version `1.*`) it will also "just work".

So I'll probably do the same thing then (if I manage to figure out how to make it all compile).

**Comment by aldanor** [comment]
Ok now. Wonder if this should be `1.2.0` or `1.1.1`?..

**Comment by tspiteri** [comment]
If there is a common practice, I agree that it makes much more sense to follow it.

As for 1.2.0 vs 1.1.1, I think a patch release is enough, as this is just removing an ergonomic obstacle, not introducing a new feature.

**Pull request merged**
